version: '2.26.0'

services:
  db:
    image: postgres:15.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=literarium_dev
      - POSTGRES_PASSWORD=literarium_dev
      - POSTGRES_DB=literarium_dev_db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on:
      - db
volumes:
  postgres_data:
  app_data:
